dependencies:
  build:
    - ruby:2.6.2
    - node:10.16.0

build_targets:
  - name: default
    build_after:
      - test_gem 
  - name: test_gem
    tags:
      channel: experimental
    build_after: 
       - setup 
    commands:
      - bundle exec tdiary test
  - name: setup
    commands:
      - gem install bundler
      - sh gemfile.sh
      - gem update --system
      - gem update bundler
      - bundle install
      - npm install
  - name: test_rack
    tags:
      channel: experimental
    build_after:
      - setup 
    commands:
      - bundle exec rake spec jasmine:ci test 

ci:
  builds:
    - name: gem_test
      build_target: test_gem
    - name: rack_test
      build_target: test_rack   
      
